// Package enums is generated by https://github.com/dekey/enumgen;
// DO NOT EDIT;
package enums

import (
	"errors"
	"fmt"
)

type (
	EnvType  string
	envTypes struct{}
)

var EnvTypes envTypes

var ErrInvalidEnv = errors.New("invalid enum")

func (e EnvType) IsValid() bool {
	switch e {
	case prod, gcpdev, staging, demo, test, dev, lint, debug, ci:
		return true
	}
	return false
}

func (e EnvType) String() string { return string(e) }

func (t envTypes) Prod() EnvType { return prod }

func (t envTypes) Gcpdev() EnvType { return gcpdev }

func (t envTypes) Staging() EnvType { return staging }

func (t envTypes) Demo() EnvType { return demo }

func (t envTypes) Test() EnvType { return test }

func (t envTypes) Dev() EnvType { return dev }

func (t envTypes) Lint() EnvType { return lint }

func (t envTypes) Debug() EnvType { return debug }

func (t envTypes) Ci() EnvType { return ci }

func (t envTypes) FromString(v string) (EnvType, error) {
	switch v {
	case prod:
		return t.Prod(), nil
	case gcpdev:
		return t.Gcpdev(), nil
	case staging:
		return t.Staging(), nil
	case demo:
		return t.Demo(), nil
	case test:
		return t.Test(), nil
	case dev:
		return t.Dev(), nil
	case lint:
		return t.Lint(), nil
	case debug:
		return t.Debug(), nil
	case ci:
		return t.Ci(), nil
	}
	return "", fmt.Errorf("env given [%s]: %w", v, ErrInvalidEnv)
}
