// Package enums_test is generated by https://github.com/dekey/enumgen;
// DO NOT EDIT;
package enums_test

import (
	"testing"

	"github.com/dekey/enums/internal/examples/enums"
)

func TestRole_Validate(t *testing.T) {
	t.Parallel()
	doEnumTest(t, map[stringEnum]bool{
		enums.RoleType("eggs"):   false,
		enums.RoleTypes.Admin():  true,
		enums.RoleTypes.Editor(): true,
		enums.RoleTypes.Viewer(): true,
	})
}
