// Package enums is generated by https://github.com/dekey/enumgen;
// DO NOT EDIT;
package enums

import (
	"errors"
	"fmt"
)

type (
	RoleType  string
	roleTypes struct{}
)

var RoleTypes roleTypes

var ErrInvalidRole = errors.New("invalid enum")

func (e RoleType) IsValid() bool {
	switch e {
	case admin, editor, viewer:
		return true
	}
	return false
}

func (e RoleType) String() string { return string(e) }

func (t roleTypes) Admin() RoleType { return admin }

func (t roleTypes) Editor() RoleType { return editor }

func (t roleTypes) Viewer() RoleType { return viewer }

func (t roleTypes) FromString(v string) (RoleType, error) {
	switch v {
	case admin:
		return t.Admin(), nil
	case editor:
		return t.Editor(), nil
	case viewer:
		return t.Viewer(), nil
	}
	return "", fmt.Errorf("role given [%s]: %w", v, ErrInvalidRole)
}
