// Code generated by enumgen; DO NOT EDIT.
package enums_test

import (
	"testing"

	"github.com/dekey/enums/internal/pkg/enums"
)

func TestEnv_Validate(t *testing.T) {
	t.Parallel()
	doEnumTest(t, map[enums.StringEnum]bool{
		enums.EnvType("eggs"): false,
		enums.EnvTypes.Prod(): true,
		enums.EnvTypes.Gcpdev(): true,
		enums.EnvTypes.Staging(): true,
		enums.EnvTypes.Demo(): true,
		enums.EnvTypes.Test(): true,
		enums.EnvTypes.Dev(): true,
		enums.EnvTypes.Lint(): true,
		enums.EnvTypes.Debug(): true,
		enums.EnvTypes.Ci(): true,
		enums.EnvTypes.Admin(): true,
		enums.EnvTypes.Editor(): true,
		enums.EnvTypes.Viewer(): true,
	})
}
