// Code generated by enumgen; DO NOT EDIT.
package enums

import (
	"errors"
	"fmt"
)

type (
	RoleType  string
	roleTypes struct{}
)

var RoleTypes roleTypes

var ErrInvalidRole = errors.New("invalid enum")

func (e RoleType) IsValid() bool {
	switch e {
	case prod, gcpdev, staging, demo, test, dev, lint, debug, ci, admin, editor, viewer:
		return true
	}
	return false
}

func (e RoleType) String() string { return string(e) }

func (t roleTypes) Prod() RoleType { return prod }

func (t roleTypes) Gcpdev() RoleType { return gcpdev }

func (t roleTypes) Staging() RoleType { return staging }

func (t roleTypes) Demo() RoleType { return demo }

func (t roleTypes) Test() RoleType { return test }

func (t roleTypes) Dev() RoleType { return dev }

func (t roleTypes) Lint() RoleType { return lint }

func (t roleTypes) Debug() RoleType { return debug }

func (t roleTypes) Ci() RoleType { return ci }

func (t roleTypes) Admin() RoleType { return admin }

func (t roleTypes) Editor() RoleType { return editor }

func (t roleTypes) Viewer() RoleType { return viewer }

func (t roleTypes) FromString(v string) (RoleType, error) {
	switch v {
	case prod:
		return t.Prod(), nil
	case gcpdev:
		return t.Gcpdev(), nil
	case staging:
		return t.Staging(), nil
	case demo:
		return t.Demo(), nil
	case test:
		return t.Test(), nil
	case dev:
		return t.Dev(), nil
	case lint:
		return t.Lint(), nil
	case debug:
		return t.Debug(), nil
	case ci:
		return t.Ci(), nil
	case admin:
		return t.Admin(), nil
	case editor:
		return t.Editor(), nil
	case viewer:
		return t.Viewer(), nil

	}
	return "", fmt.Errorf("role given [%s]: %w", v, ErrInvalidRole)
}
