// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CodeGenerator is an autogenerated mock type for the CodeGenerator type
type CodeGenerator struct {
	mock.Mock
}

// GenerateCode provides a mock function with given fields: pkg, name, consts
func (_m *CodeGenerator) GenerateCode(pkg string, name string, consts []string) []byte {
	ret := _m.Called(pkg, name, consts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCode")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, []string) []byte); ok {
		r0 = rf(pkg, name, consts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// GenerateTests provides a mock function with given fields: pkg, pkgDir, importPath, name, consts
func (_m *CodeGenerator) GenerateTests(pkg string, pkgDir string, importPath string, name string, consts []string) error {
	ret := _m.Called(pkg, pkgDir, importPath, name, consts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) error); ok {
		r0 = rf(pkg, pkgDir, importPath, name, consts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCodeGenerator creates a new instance of CodeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeGenerator {
	mock := &CodeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
