// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Locator is an autogenerated mock type for the Locator type
type Locator struct {
	mock.Mock
}

// FindRootDirFrom provides a mock function with given fields: startDir, file
func (_m *Locator) FindRootDirFrom(startDir string, file string) (string, error) {
	ret := _m.Called(startDir, file)

	if len(ret) == 0 {
		panic("no return value specified for FindRootDirFrom")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(startDir, file)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(startDir, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(startDir, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadModulePath provides a mock function with given fields: root
func (_m *Locator) ReadModulePath(root string) (string, error) {
	ret := _m.Called(root)

	if len(ret) == 0 {
		panic("no return value specified for ReadModulePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(root)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(root)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(root)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelativePackagePath provides a mock function with given fields: modRoot, fullPath
func (_m *Locator) RelativePackagePath(modRoot string, fullPath string) (string, error) {
	ret := _m.Called(modRoot, fullPath)

	if len(ret) == 0 {
		panic("no return value specified for RelativePackagePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(modRoot, fullPath)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(modRoot, fullPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(modRoot, fullPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLocator creates a new instance of Locator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Locator {
	mock := &Locator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
