// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// ParseFromFile provides a mock function with given fields: packageDir, goFile, goLine
func (_m *Parser) ParseFromFile(packageDir string, goFile string, goLine string) (string, []string, error) {
	ret := _m.Called(packageDir, goFile, goLine)

	if len(ret) == 0 {
		panic("no return value specified for ParseFromFile")
	}

	var r0 string
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, []string, error)); ok {
		return rf(packageDir, goFile, goLine)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(packageDir, goFile, goLine)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) []string); ok {
		r1 = rf(packageDir, goFile, goLine)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(packageDir, goFile, goLine)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
